# Generated by Django 4.2.30 on 2026-08-27 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('identification_card', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de Cédula')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección Domiciliar')),
                ('emergency_contact_name', models.CharField(max_length=150, verbose_name='Nombre de Contacto de Emergencia')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name='Teléfono de Emergencia')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parentesco')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Número de Expediente')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Expediente Clínico',
                'verbose_name_plural': 'Expedientes Clínicos',
            },
        ),
    ]
