# Generated by Django 4.2.30 on 2026-08-28 08:01

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        TrigramExtension(), 
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'verbose_name': 'Expediente Digital', 'verbose_name_plural': 'Expedientes Digitales'},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Iniciales'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Expediente'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name'], name='patient_first_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=django.contrib.postgres.indexes.GinIndex(fields=['last_name'], name='patient_last_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
