# Generated by Django 4.2.30 on 2026-08-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_alter_medicalrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('reason', models.TextField(verbose_name='Motivo de Consulta')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Síntomas / Cuadro Clínico')),
                ('physical_examination', models.TextField(blank=True, null=True, verbose_name='Examen Físico')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True, verbose_name='Presión Arterial (mmHg)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('heart_rate_bpm', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Cardíaca (lpm)')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria (rpm)')),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Saturación O2 (%)')),
                ('diagnosis', models.TextField(verbose_name='Diagnóstico')),
                ('treatment_plan', models.TextField(blank=True, null=True, verbose_name='Plan de Tratamiento / Receta')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones Adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Médico Atendiente')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.medicalrecord', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-consultation_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=50, verbose_name='Número de Expediente')),
                ('action', models.CharField(choices=[('CREATE', 'Creación de Consulta'), ('UPDATE', 'Modificación de Consulta'), ('DELETE', 'Eliminación de Consulta')], max_length=10)),
                ('performed_by', models.CharField(max_length=150, verbose_name='Usuario Responsable')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict, verbose_name='Detalles del Cambio')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='patients.consultation')),
            ],
            options={
                'verbose_name': 'Bitácora de Auditoría Clínica',
                'verbose_name_plural': 'Bitácoras de Auditoría Clínica',
                'ordering': ['-timestamp'],
            },
        ),
    ]
