# Generated by Django 4.2.30 on 2026-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_consultation_clinicalauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('O+', 'O Positivo (O+)'), ('O-', 'O Negativo (O-)'), ('A+', 'A Positivo (A+)'), ('A-', 'A Negativo (A-)'), ('B+', 'B Positivo (B+)'), ('B-', 'B Negativo (B-)'), ('AB+', 'AB Positivo (AB+)'), ('AB-', 'AB Negativo (AB-)')], max_length=5, null=True, verbose_name='Tipo de Sangre'),
        ),
    ]
