# Generated by Django 4.2.30 on 2026-10-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
