# Generated by Django 4.2.30 on 2026-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura (m)'),
        ),
    ]
