# Generated by Django 4.2.30 on 2026-09-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_consultation_height_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='allergies',
            field=models.TextField(blank=True, help_text='Alergias a medicamentos, alimentos u otras sustancias', null=True, verbose_name='Alergias Conocidas'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='family_background',
            field=models.TextField(blank=True, help_text='Antecedentes de diabetes, hipertensión o cáncer familiar', null=True, verbose_name='Antecedentes Heredofamiliares'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_background',
            field=models.TextField(blank=True, help_text='Enfermedades crónicas, cirugías previas, etc.', null=True, verbose_name='Antecedentes Médicos / Patológicos'),
        ),
    ]
