# Generated by Django 4.2.30 on 2026-09-04 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_medicalrecord_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=patients.models.consultation_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Archivo')),
                ('title', models.CharField(max_length=150, verbose_name='Título / Descripción del Estudio')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.consultation', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Estudio / Documento Adjunto',
                'verbose_name_plural': 'Estudios / Documentos Adjuntos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
