# Generated by Django 4.2.30 on 2026-09-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Programada'), ('WAITING', 'En Sala de Espera'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No asistió')], default='SCHEDULED', max_length=20, verbose_name='Estado'),
        ),
    ]
