# Generated by Django 4.2.30 on 2026-10-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_consultation_is_active'),
        ('patients', '0009_alter_appointment_status'),
    ]

    operations = [
    ]
