# Generated by Django 4.2.30 on 2026-10-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionalconfiguration',
            name='name',
            field=models.CharField(default='Centro de Salud', max_length=200),
        ),
    ]
