# Generated by Django 4.2.30 on 2026-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_alter_institutionalconfiguration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='campaign_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='campaign_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='certification_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='certification_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='emergency_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='emergency_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='emergency_phone_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='hours_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='information_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='information_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='mission_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='mission_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='saturday_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='saturday_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='weekday_hours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institutionalconfiguration',
            name='weekday_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
