# Generated by Django 4.2.30 on 2026-08-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Administrador de TI'), ('DOCTOR', 'Personal Médico'), ('ADMISSION', 'Personal de Admisión'), ('DIRECTOR', 'Dirección del Centro')], max_length=20, unique=True),
        ),
    ]
