# Generated by Django 4.2.30 on 2026-10-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_security_answer_1_user_security_answer_2_and_more'),
    ]

    operations = [
    ]
